# Generated by Django 2.2.4 on 2019-10-04 03:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191004_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
