# Generated by Django 2.2.4 on 2019-10-10 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sale_datetime_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='low_stock_threshold',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
